---
name: Bug Report
about: Create a report to help us improve
title: ''
labels: ''
assignees: ''

---

**Describe the bug**
  Give a clear and concise description of what the bug is.

**Prerequisites**
Please go through the following questions for yourself before submitting an issue. 

-  I am running the latest version
-  I checked the documentation and found no answer
-  I checked to make sure that this issue has not already been filed
-  I'm reporting the issue to the correct repository (for multi-repository projects)


**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what behaviour were you expecting.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.