import "./globals.css";
import Navbar from "@/components/Navbar";
export const metadata = {
  title: "Carbon",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="w-full bg-[#152023] font-sans text-white mt-20 px-8 md:px-12 py-4">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
