import "./globals.css";
import Navbar from "@/components/Navbar";
export const metadata = {
  title: "Carbon",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="w-full bg-[#12323f] font-mono text-white mt-16">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
