import "./globals.css";
import ProviderWrapper from "./ProviderWrapper";
export const metadata = {
  title: "Carbonops",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
      </head>
      <body className="w-full bg-[#152023] font-sans text-white">
        <ProviderWrapper>
        {children}
         </ProviderWrapper>
      </body>
    </html>
  );
}
